# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  menu:
    taskfile: ./Taskmenu.yaml
    flatten: true

tasks:
  # Add your project tasks here

  # Example usage
  standalone-task:
    desc: a top-level task with no submenu
    cmds:
      - echo "a top-level task with no submenu"

  task-and-menu:
    desc: a task that is also a menu prefix for nested tasks
    cmds:
      - echo "a task that is also a menu prefix for nested tasks"

  task-and-menu:nested-task:
    desc: a task nested under another task's menu prefix
    cmds:
      - echo "a task nested under another task's menu prefix"